### ISSUE TITLE
Additional front ends?

### ISSUE THREAD

**Issue by larsbrinkhoff** [tromey/el-compilador#15]
Is there a design to attach different front ends?

**Comment by tromey** [comment]
I haven't really thought about it.  I guess you could either generate the IR directly or translate to elisp.

**Comment by larsbrinkhoff** [comment]
Thanks.  I have been wanting to compile CL to bytecodes for a long time.  I already have a compiler which generates intermediate elisp, but I think going to lapcode or some other IR would be better.
