### ISSUE TITLE
SSA vs CPS for Lisp?

### ISSUE THREAD

**Issue by larsbrinkhoff** [tromey/el-compilador#2]
Hello,

I'm interested in Lisp compiler technology.  I see you chose the SSA framework for your compiler.  Some other compilers for functional-ish languages use CPS.  Do you have an opinion on whether SSA or CPS is best suited for compiling Lisp?

**Comment by tromey** [comment]
I don't really have an opinion.  For me the story was that I knew a bit about SSA and wanted to understand it more.  There were some articles about this though - some on Wingo's blog and also one on the MLton list, IIRC mostly in favor of SSA.

**Comment by larsbrinkhoff** [comment]
I did have Wingo's blog in mind, condsering that he chose CPS for the Guile compiler, but later seemed to have second thoughts.  I'll check out the MLton list.

Thanks!
